project:
  type: book

book:
  title: "mybook"
  author: "Jane Doe"
  date: "19/07/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - demo.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
