project:
  output-dir: _slides
  render:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

title: "test"
author: "Jane Doe"
date: "25/07/2022"
bibliography: references.bib

format: revealjs
